[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "/plugins/netlify-plugin-hello-world"
  
[[plugins]]
package = "@netlify/plugin-sitemap"
